# Database Configuration
# Available types: mysql, sqlite

# Database type
type: "mysql"

# MySQL settings (only used if type is mysql)
host: "localhost"
port: 3306
database: "frizzlenstore"
username: "root"
password: ""

# Connection pool settings
pool:
  # Minimum number of connections
  min_connections: 2
  # Maximum number of connections
  max_connections: 10
  # Connection timeout in milliseconds
  timeout: 30000
  # Maximum lifetime of a connection in milliseconds
  max_lifetime: 1800000 